import {
  AppstoreOutlined,
  AuditOutlined,
  CloudServerOutlined,
  CreditCardOutlined,
  CustomerServiceOutlined,
  DashboardOutlined,
  GiftOutlined,
  SafetyOutlined,
  SettingOutlined,
  TeamOutlined,
} from "@ant-design/icons";
import type { ReactNode } from "react";
export type NavItem = {
  path: string;
  title: string;
  group: string;
  icon: ReactNode;
  permission?: string;
};
export const adminNav: NavItem[] = [
  { path: "user-groups", title: "用户组管理", group: "用户运营", icon: <TeamOutlined />, permission: "iam.user.read" },
  { path: "routing", title: "路由管理", group: "节点网络", icon: <CloudServerOutlined />, permission: "node.read" },
  { path: "commission-settings", title: "邀请与佣金设置", group: "平台配置", icon: <SettingOutlined />, permission: "billing.order.read" },
  { path: "telegram", title: "Telegram 设置", group: "平台配置", icon: <SettingOutlined />, permission: "security.audit.read" },
  {
    path: "overview",
    title: "概览",
    group: "工作台",
    icon: <DashboardOutlined />,
    permission: "billing.ledger.read",
  },
  {
    path: "users",
    title: "用户",
    group: "用户运营",
    icon: <TeamOutlined />,
    permission: "iam.user.read",
  },
  {
    path: "tickets",
    title: "工单",
    group: "用户运营",
    icon: <CustomerServiceOutlined />,
    permission: "ops.ticket.read",
  },
  {
    path: "device-limits",
    title: "设备限制",
    group: "用户运营",
    icon: <SafetyOutlined />,
    permission: "iam.user.read",
  },
  {
    path: "bulk",
    title: "批量运营",
    group: "用户运营",
    icon: <TeamOutlined />,
    permission: "iam.user.read",
  },
  {
    path: "servers",
    title: "服务器",
    group: "节点网络",
    icon: <CloudServerOutlined />,
    permission: "node.read",
  },
  {
    path: "nodes",
    title: "节点",
    group: "节点网络",
    icon: <CloudServerOutlined />,
    permission: "node.read",
  },
  {
    path: "node-pools",
    title: "权限组",
    group: "节点网络",
    icon: <CloudServerOutlined />,
    permission: "node.read",
  },
  {
    path: "traffic-resets",
    title: "流量重置",
    group: "节点网络",
    icon: <DashboardOutlined />,
    permission: "metering.reset.read",
  },
  {
    path: "plans",
    title: "套餐",
    group: "订阅与财务",
    icon: <AppstoreOutlined />,
    permission: "catalog.read",
  },
  {
    path: "orders",
    title: "订单",
    group: "订阅与财务",
    icon: <CreditCardOutlined />,
    permission: "billing.order.read",
  },
  {
    path: "late-payments",
    title: "待处理款项",
    group: "订阅与财务",
    icon: <CreditCardOutlined />,
    permission: "billing.ledger.read",
  },
  {
    path: "coupons",
    title: "优惠券",
    group: "营销推广",
    icon: <GiftOutlined />,
    permission: "marketing.coupon.write",
  },
  {
    path: "gift-cards",
    title: "礼品卡",
    group: "营销推广",
    icon: <GiftOutlined />,
    permission: "marketing.giftcard.read",
  },
  {
    path: "commissions",
    title: "分销",
    group: "营销推广",
    icon: <TeamOutlined />,
    permission: "billing.order.read",
  },
  {
    path: "payment-providers",
    title: "支付渠道",
    group: "订阅与财务",
    icon: <CreditCardOutlined />,
    permission: "billing.payment.read",
  },
  {
    path: "notifications",
    title: "通知设置",
    group: "内容与通知",
    icon: <SettingOutlined />,
    permission: "security.audit.read",
  },
  {
    path: "announcements",
    title: "公告",
    group: "内容与通知",
    icon: <CustomerServiceOutlined />,
    permission: "ops.announcement.write",
  },
  {
    path: "content",
    title: "知识库",
    group: "内容与通知",
    icon: <AppstoreOutlined />,
    permission: "ops.content.write",
  },
  {
    path: "appearance",
    title: "外观",
    group: "系统设置",
    icon: <AppstoreOutlined />,
    permission: "platform.appearance.read",
  },
  {
    path: "plugins",
    title: "插件",
    group: "系统设置",
    icon: <AppstoreOutlined />,
    permission: "platform.plugin.read",
  },
  {
    path: "risk",
    title: "风控",
    group: "安全与运维",
    icon: <SafetyOutlined />,
    permission: "security.audit.read",
  },
  {
    path: "switches",
    title: "降级开关",
    group: "安全与运维",
    icon: <SettingOutlined />,
    permission: "security.audit.read",
  },
  {
    path: "audit",
    title: "审计日志",
    group: "安全与运维",
    icon: <AuditOutlined />,
    permission: "security.audit.read",
  },
];
export const portalNav: NavItem[] = [
  {
    path: "overview",
    title: "概览",
    group: "我的账户",
    icon: <DashboardOutlined />,
  },
  {
    path: "subscriptions",
    title: "我的订阅",
    group: "我的账户",
    icon: <CloudServerOutlined />,
  },
  {
    path: "orders",
    title: "我的订单",
    group: "我的账户",
    icon: <CreditCardOutlined />,
  },
  {
    path: "plans",
    title: "选购套餐",
    group: "服务",
    icon: <AppstoreOutlined />,
  },
  { path: "gifts", title: "兑换礼品卡", group: "服务", icon: <GiftOutlined /> },
  {
    path: "support",
    title: "工单支持",
    group: "服务",
    icon: <CustomerServiceOutlined />,
  },
  {
    path: "help",
    title: "帮助中心",
    group: "服务",
    icon: <AppstoreOutlined />,
  },
  {
    path: "referrals",
    title: "邀请返利",
    group: "我的账户",
    icon: <TeamOutlined />,
  },
  {
    path: "account",
    title: "账号安全",
    group: "我的账户",
    icon: <SafetyOutlined />,
  },
];
