-- Xboard / V2board 兼容的节点对接协议（UniProxy）。
--
-- 目的：让现成的 V2bX / XrayR 不加改造就能接入本平台。它们已经稳定支持
-- xray-core、sing-box、hysteria2 三套内核，自研节点端在协议覆盖上短期内追不上，
-- 也没必要追 —— 平台的价值在用户、订阅、计费与调度，不在数据面转发。
--
-- 兼容协议带来的两个结构性约束，这里一并处理：
--
--  1. UniProxy 的用户 ID 是**整数**，而本平台主键是 UUIDv7。
--     直接把 UUID 截断成整数会碰撞，因此给订阅另加一个自增的对外编号。
--
--  2. push 接口只提交 {uid:[上行,下行]} 的增量，**没有幂等键**。
--     协议层面无法杜绝重复累加，只能在接收侧按「同节点+同窗口」做近似去重，
--     并把每次上报原样留档，事后可对账。这一点是协议的固有缺陷，不是实现缺陷。

-- +goose Up

--------------------------------------------------------------------------------
-- 订阅的对外整数编号
--------------------------------------------------------------------------------

-- +goose StatementBegin
-- IDENTITY 而非 serial：前者是标准语法，且不会因为手工插入而把序列甩在后面。
ALTER TABLE subscriptions
  ADD COLUMN node_uid bigint GENERATED BY DEFAULT AS IDENTITY;

-- 节点侧每次拉全量用户列表都要按它排序与去重，必须唯一且有索引
CREATE UNIQUE INDEX subscriptions_node_uid_key ON subscriptions (node_uid);

COMMENT ON COLUMN subscriptions.node_uid IS
  'UniProxy 协议要求的整数用户 ID。仅用于节点对接，对外仍以 UUID 为准。';
-- +goose StatementEnd

--------------------------------------------------------------------------------
-- 节点的协议配置与接入令牌
--------------------------------------------------------------------------------

-- +goose StatementBegin
ALTER TABLE nodes
  -- UniProxy 的 node_type：v2ray / vless / trojan / shadowsocks / hysteria / tuic / anytls
  ADD COLUMN node_type text,
  -- 对外服务端口与域名，下发给节点端与订阅生成器
  ADD COLUMN server_host text,
  ADD COLUMN server_port int CHECK (server_port IS NULL OR server_port BETWEEN 1 AND 65535),
  -- 协议细节（传输方式、TLS、Reality 公钥等），结构随 node_type 变化
  ADD COLUMN protocol_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  -- 流量倍率：某些线路成本高，按倍率折算计费
  ADD COLUMN traffic_rate numeric(6,2) NOT NULL DEFAULT 1.00
    CHECK (traffic_rate >= 0),
  -- 节点端拉取用户列表用的令牌，只存哈希（与 bootstrap_token 同样处理）
  ADD COLUMN server_token_hash bytea,
  -- 用户可见的展示信息
  ADD COLUMN display_name text,
  ADD COLUMN sort_order int NOT NULL DEFAULT 0;

CREATE INDEX idx_nodes_serving ON nodes (tenant_id, node_type, sort_order)
  WHERE status = 'active' AND node_type IS NOT NULL;

COMMENT ON COLUMN nodes.server_token_hash IS
  '节点端 UniProxy 请求携带的 token 的哈希。明文只在签发时返回一次。';
-- +goose StatementEnd

--------------------------------------------------------------------------------
-- 套餐与节点组的可见性（XBD-010：未授权用户无法获得组内资源）
--------------------------------------------------------------------------------

-- +goose StatementBegin
-- 一个节点可属于多个组，一个套餐版本授权若干组。
-- 用中间表而不是数组：数组无法建外键，节点组被删时会留下悬空引用。
CREATE TABLE node_group_members (
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  pool_id   uuid NOT NULL,
  node_id   uuid NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
  PRIMARY KEY (pool_id, node_id),
  CONSTRAINT node_group_members_pool_fk
    FOREIGN KEY (tenant_id, pool_id) REFERENCES node_pools (tenant_id, id) ON DELETE CASCADE
);
SELECT app.enable_tenant_rls('node_group_members');

CREATE TABLE plan_node_pools (
  tenant_id       uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  plan_version_id uuid NOT NULL,
  pool_id         uuid NOT NULL,
  PRIMARY KEY (plan_version_id, pool_id),
  CONSTRAINT plan_node_pools_version_fk
    FOREIGN KEY (tenant_id, plan_version_id) REFERENCES plan_versions (tenant_id, id) ON DELETE CASCADE,
  CONSTRAINT plan_node_pools_pool_fk
    FOREIGN KEY (tenant_id, pool_id) REFERENCES node_pools (tenant_id, id) ON DELETE CASCADE
);
SELECT app.enable_tenant_rls('plan_node_pools');

COMMENT ON TABLE plan_node_pools IS
  'XBD-010：套餐版本授权的资源池。节点端拉用户列表时据此过滤，未授权套餐的用户拿不到该节点。';
-- +goose StatementEnd

--------------------------------------------------------------------------------
-- 节点流量上报留档
--------------------------------------------------------------------------------

-- +goose StatementBegin
-- UniProxy 的 push 没有幂等键，无法在协议层杜绝重复。
-- 这张表把每一次上报原样留下：出现争议时可以逐笔回溯，
-- 也是「重复上报导致多扣流量」这类投诉唯一的证据来源。
CREATE TABLE node_traffic_reports (
  id           uuid PRIMARY KEY DEFAULT uuidv7(),
  tenant_id    uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  node_id      uuid NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
  -- 上报中包含的用户数与合计流量，便于快速判断异常批次
  user_count   int NOT NULL DEFAULT 0,
  total_upload bigint NOT NULL DEFAULT 0,
  total_download bigint NOT NULL DEFAULT 0,
  traffic_rate numeric(6,2) NOT NULL DEFAULT 1.00,
  -- 原始报文，追加写
  raw_payload  jsonb NOT NULL,
  -- 近似去重：同一节点在极短时间内的重复提交视为网络重试
  content_hash bytea NOT NULL,
  duplicate_of uuid REFERENCES node_traffic_reports(id) ON DELETE SET NULL,
  received_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_node_traffic_reports_node ON node_traffic_reports (node_id, received_at DESC);
-- 去重窗口内的快速查找
CREATE INDEX idx_node_traffic_reports_dedup ON node_traffic_reports (node_id, content_hash, received_at DESC);

SELECT app.enable_tenant_rls('node_traffic_reports');
SELECT app.make_append_only('node_traffic_reports');
-- +goose StatementEnd

--------------------------------------------------------------------------------
-- 节点在线设备（alive 接口，用于 XBD-008 设备数限制）
--------------------------------------------------------------------------------

-- +goose StatementBegin
CREATE TABLE node_alive_ips (
  tenant_id       uuid NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  node_id         uuid NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
  subscription_id uuid NOT NULL REFERENCES subscriptions(id) ON DELETE CASCADE,
  -- 只存 IP 的哈希：在线设备数是运营指标，不需要保留可回溯到个人的原始地址
  ip_hash         bytea NOT NULL,
  last_seen_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (node_id, subscription_id, ip_hash)
);

CREATE INDEX idx_node_alive_recent ON node_alive_ips (subscription_id, last_seen_at DESC);

SELECT app.enable_tenant_rls('node_alive_ips');

COMMENT ON TABLE node_alive_ips IS
  'XBD-008 设备数限制的数据来源。只存 IP 哈希，过期数据由清理任务删除。';
-- +goose StatementEnd

-- +goose Down

-- +goose StatementBegin
DROP TABLE IF EXISTS node_alive_ips;
DROP TABLE IF EXISTS node_traffic_reports;
DROP TABLE IF EXISTS plan_node_pools;
DROP TABLE IF EXISTS node_group_members;
ALTER TABLE nodes
  DROP COLUMN IF EXISTS node_type,
  DROP COLUMN IF EXISTS server_host,
  DROP COLUMN IF EXISTS server_port,
  DROP COLUMN IF EXISTS protocol_config,
  DROP COLUMN IF EXISTS traffic_rate,
  DROP COLUMN IF EXISTS server_token_hash,
  DROP COLUMN IF EXISTS display_name,
  DROP COLUMN IF EXISTS sort_order;
DROP INDEX IF EXISTS subscriptions_node_uid_key;
ALTER TABLE subscriptions DROP COLUMN IF EXISTS node_uid;
-- +goose StatementEnd
