#!/usr/bin/env bash
# [INPUT]: 依赖 PSQL（默认 /opt/aegispanel/deploy/psql.sh）、admin / node / public 三个网关、易支付测试商户 1001，依赖三个一次性库确认变量
# [OUTPUT]: UniProxy（Xboard 兼容）数据面契约：节点认证、配置与 ETag、用户资格与池隔离、流量上报去重与倍率、在线上报；清理失败时把失败的 SQL 与库的报错打到 stderr
# [POS]: panel/tests 的数据面脚本，由 deploy/run-smoke-e2e.sh 在冒烟栈上跑；节点接入与上线由联调冒烟 seed.ts 的两阶段接入覆盖，这里用 SQL 夹具直接造 serving 节点
# [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
# UniProxy end-to-end contract test (Xboard / V2board compatible data plane).
#
# This test deliberately creates a fixture through SQL because Server/Node lifecycle
# is covered by the smoke seed's two-phase enrolment (frontend/tests/smoke/seed.ts). The fixture still has to satisfy the current stable
# serving contract: a ready Server, an active logical Node, protocol schema v1 and
# a non-null validation timestamp. Every network and database operation fails closed.
# Required safety acknowledgements (the database name must also contain test/e2e):
#   UNIPROXY_E2E_DISPOSABLE=YES_DELETE_FIXTURES
#   UNIPROXY_E2E_DATABASE=<exact current_database() value>
#   UNIPROXY_E2E_TENANT_ID=<exact disposable tenant UUID>
set -euo pipefail

ADM=${ADM:-http://127.0.0.1:9001}
NODE=${NODE:-http://127.0.0.1:9003}
PUB=${PUB:-http://127.0.0.1:9000}
PSQL=${PSQL:-/opt/aegispanel/deploy/psql.sh}
ADMIN_EMAIL=${ADMIN_EMAIL:-}
ADMIN_PASS=${ADMIN_PASS:-}
TENANT=${UNIPROXY_E2E_TENANT_ID:-}
UNI="$NODE/api/v1/server/UniProxy"

pass=0
HTTP_CODE=
HTTP_BODY=
HTTP_HEADERS=
HTTP_REQUEST_ID=
E2E_PREFLIGHT_OK=0
DISPOSABLE_RESIDUE_EXPECTED=0
TEMP_FILES=()
NODE_ID=
SERVER_ID=
INITIAL_POOL_ID=
UNAUTH_POOL_ID=
ELIGIBLE_POOL_ID=
USER_ID=
REGISTRATION_ID=
SUB_ID=
ORDER_ID=
PV=
UE=

ok() { echo "  [ OK ] $1"; pass=$((pass + 1)); }
die() { echo "  [FAIL] $1" >&2; [ -z "${2:-}" ] || echo "         $2" >&2; exit 1; }
sec() { echo; echo "=== $1 ==="; }
assert_eq() { [ "$1" = "$2" ] || die "$3" "values did not match"; ok "$3"; }
assert_nonempty() { [ -n "$1" ] || die "$2" "value is empty"; ok "$2"; }

is_uuid() {
  [[ ${1:-} =~ ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$ ]]
}

require_loopback_url() {
  python3 -c '
import sys, urllib.parse
u = urllib.parse.urlsplit(sys.argv[1])
ok = (
    u.scheme in {"http", "https"}
    and u.hostname in {"127.0.0.1", "::1"}
    and u.port is not None
    and u.username is None and u.password is None
    and u.path in {"", "/"} and not u.query and not u.fragment
)
raise SystemExit(0 if ok else 1)
' "$1" >/dev/null 2>&1 || die "$2 must be an explicit numeric loopback origin with a port"
}

register_temp() {
  TEMP_FILES+=("$1")
}

# stderr 不吞：清理失败时要看得出是哪一句、库回了什么
cleanup_sql() {
  [ "$E2E_PREFLIGHT_OK" = 1 ] || return 0
  "$PSQL" -X -v ON_ERROR_STOP=1 -c "$1" >/dev/null && return 0
  echo "  [cleanup] SQL failed: $1" >&2
  return 1
}

cleanup() {
  local status=$? cleanup_failed=0 f
  trap - EXIT INT TERM
  set +e

  # All identifiers used below were either generated by this script or passed
  # through db_scalar's UUID validators. Each statement is deliberately scoped
  # to an exact fixture identifier; never clean by prefix, age or wildcard.
  if is_uuid "$NODE_ID"; then
    cleanup_sql "DELETE FROM node_alive_ips WHERE tenant_id='$TENANT' AND node_id='$NODE_ID'" || cleanup_failed=1
  fi
  if is_uuid "$USER_ID"; then
    cleanup_sql "DELETE FROM refresh_tokens WHERE tenant_id='$TENANT' AND user_id='$USER_ID'" || cleanup_failed=1
    cleanup_sql "DELETE FROM sessions WHERE tenant_id='$TENANT' AND user_id='$USER_ID'" || cleanup_failed=1
  fi
  if is_uuid "$REGISTRATION_ID"; then
    cleanup_sql "DELETE FROM registration_sessions WHERE tenant_id='$TENANT' AND id='$REGISTRATION_ID'" || cleanup_failed=1
  fi

  # Before registration completion, every fixture row is reversible and must
  # be removed precisely. Registration completion and later operations create
  # immutable security/audit/ledger evidence, so from that boundary onward the
  # mandatory disposable database is the cleanup unit and must be discarded.
  if [ "$DISPOSABLE_RESIDUE_EXPECTED" = 0 ]; then
    if is_uuid "$ORDER_ID"; then
      cleanup_sql "DELETE FROM orders WHERE tenant_id='$TENANT' AND id='$ORDER_ID'" || cleanup_failed=1
    fi
    if is_uuid "$SUB_ID"; then
      cleanup_sql "DELETE FROM subscriptions WHERE tenant_id='$TENANT' AND id='$SUB_ID'" || cleanup_failed=1
    fi
    if is_uuid "$USER_ID"; then
      cleanup_sql "DELETE FROM users WHERE tenant_id='$TENANT' AND id='$USER_ID'" || cleanup_failed=1
    fi
    if is_uuid "$NODE_ID"; then
      cleanup_sql "DELETE FROM nodes WHERE tenant_id='$TENANT' AND id='$NODE_ID'" || cleanup_failed=1
    fi
    if is_uuid "$SERVER_ID"; then
      cleanup_sql "DELETE FROM servers WHERE tenant_id='$TENANT' AND id='$SERVER_ID'" || cleanup_failed=1
    fi
    if is_uuid "$INITIAL_POOL_ID"; then
      cleanup_sql "DELETE FROM node_pools WHERE tenant_id='$TENANT' AND id='$INITIAL_POOL_ID'" || cleanup_failed=1
    fi
    if is_uuid "$UNAUTH_POOL_ID"; then
      cleanup_sql "DELETE FROM node_pools WHERE tenant_id='$TENANT' AND id='$UNAUTH_POOL_ID'" || cleanup_failed=1
    fi
  fi

  for f in "${TEMP_FILES[@]:-}"; do
    if [ -n "$f" ] && ! rm -f -- "$f"; then
      cleanup_failed=1
    fi
  done

  if [ "$cleanup_failed" -ne 0 ]; then
    echo "  [FAIL] exact reversible fixture cleanup was incomplete" >&2
    [ "$status" -ne 0 ] || status=1
  elif [ "$status" -eq 0 ]; then
    echo
    echo "==============================================="
    echo "  passed $pass checks"
    [ "$DISPOSABLE_RESIDUE_EXPECTED" = 0 ] \
      || echo "  discard the acknowledged disposable database"
    echo "==============================================="
  fi
  exit "$status"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

request_diag() {
  local method=$1 url=$2 path clean_url
  clean_url=${url%%\?*}
  path=$(python3 -c 'import sys, urllib.parse; print(urllib.parse.urlsplit(sys.argv[1]).path)' "$clean_url" 2>/dev/null) || path='<invalid-path>'
  printf '%s path=%s status=%s request-id=%s' "$method" "$path" "${HTTP_CODE:-transport-error}" "${HTTP_REQUEST_ID:-none}"
}

request() {
  local method=$1 url=$2 body_file header_file error_file
  shift 2
  body_file=$(mktemp)
  register_temp "$body_file"
  header_file=$(mktemp)
  register_temp "$header_file"
  error_file=$(mktemp)
  register_temp "$error_file"
  HTTP_CODE=
  HTTP_BODY=
  HTTP_HEADERS=
  HTTP_REQUEST_ID=
  if ! HTTP_CODE=$(curl -q --noproxy '*' --silent --connect-timeout 5 --max-time 30 \
      -D "$header_file" -o "$body_file" -w '%{http_code}' -X "$method" "$url" "$@" 2>"$error_file"); then
    die "HTTP transport failed" "$(request_diag "$method" "$url")"
  fi
  [[ "$HTTP_CODE" =~ ^[0-9]{3}$ ]] || {
    HTTP_CODE=invalid
    die "curl returned an invalid HTTP status" "$(request_diag "$method" "$url")"
  }
  HTTP_BODY=$(<"$body_file")
  HTTP_HEADERS=$(<"$header_file")
  HTTP_REQUEST_ID=$(awk 'BEGIN{IGNORECASE=1} /^X-Request-ID:/{sub(/\r$/, ""); print $2}' "$header_file" | tail -1)
  rm -f "$body_file" "$header_file" "$error_file"
}

expect_http() {
  local expected=$1 method=$2 url=$3
  shift 3
  request "$method" "$url" "$@"
  [ "$HTTP_CODE" = "$expected" ] || die "HTTP status assertion failed (expected $expected)" "$(request_diag "$method" "$url")"
}

json_get() {
  local body=$1 path=$2
  printf '%s' "$body" | python3 -c '
import json, sys
value = json.load(sys.stdin)
for part in sys.argv[1].split("."):
    value = value[int(part)] if isinstance(value, list) else value[part]
if value is None:
    raise SystemExit(2)
print("true" if value is True else "false" if value is False else value)
' "$path"
}

parse_registration_start() {
  printf '%s' "$1" | python3 -c '
import json, sys
d = json.load(sys.stdin)
if not isinstance(d, dict): raise SystemExit(1)
token = d.get("registration_token")
verify = d.get("verification_required")
if not isinstance(token, str) or not token or type(verify) is not bool:
    raise SystemExit(1)
if verify:
    code = d.get("dev_code")
    if not isinstance(code, str) or not code: raise SystemExit(1)
else:
    if "dev_code" in d: raise SystemExit(1)
    code = "-"
print(token)
print("true" if verify else "false")
print(code)
'
}

registration_parser_selftest() {
  local got sample
  got=$(parse_registration_start '{"registration_token":"t","verification_required":false}' | tr -d '\r') \
    || return 1
  [[ "$got" == $'t\nfalse\n-' ]] || return 1
  got=$(parse_registration_start '{"registration_token":"t","verification_required":true,"dev_code":"123456"}' | tr -d '\r') \
    || return 1
  [[ "$got" == $'t\ntrue\n123456' ]] || return 1
  for sample in \
    '{"registration_token":"t","verification_required":true}' \
    '{"registration_token":"t","verification_required":true,"dev_code":""}' \
    '{"registration_token":"t"}' \
    '{"registration_token":"t","verification_required":null}' \
    '{"registration_token":"t","verification_required":"false"}' \
    '{"registration_token":"t","verification_required":0}' \
    '{"registration_token":"t","verification_required":false,"dev_code":"123456"}' \
    '{"registration_token":"t","verification_required":true,"dev_code":123456}' \
    '{malformed'; do
    if parse_registration_start "$sample" >/dev/null 2>&1; then
      return 1
    fi
  done
  return 0
}

json_check() {
  local body=$1 expression=$2 message=$3
  if ! printf '%s' "$body" | python3 -c '
import json, sys
d = json.load(sys.stdin)
safe_globals = {"__builtins__": {}, "any": any, "str": str}
if not eval(sys.argv[1], safe_globals, {"d": d}):
    raise SystemExit(1)
' "$expression"; then
    die "$message" "response JSON assertion failed"
  fi
  ok "$message"
}

db_scalar() {
  local type=$1 query=$2 raw out
  # COPY CSV gives NULL (\\N), empty string (""), every row and every column an
  # explicit representation. Command substitution may trim terminal newlines,
  # but it cannot erase a trailing NULL/empty row as it did with plain -At output.
  if ! raw=$("$PSQL" -X -v ON_ERROR_STOP=1 -qAtc \
      "COPY ($query) TO STDOUT WITH (FORMAT csv, NULL '\\N')"); then
    die "database scalar query failed"
  fi
  if ! out=$(printf '%s' "$raw" | python3 -c '
import csv, io, sys
rows = list(csv.reader(io.StringIO(sys.stdin.read())))
if len(rows) != 1:
    raise SystemExit(2)
if len(rows[0]) != 1:
    raise SystemExit(3)
value = rows[0][0]
if value in {"", r"\N"}:
    raise SystemExit(4)
sys.stdout.write(value)
'); then
    die "database scalar query did not return exactly one non-null, non-empty cell"
  fi
  case "$type" in
    integer) [[ "$out" =~ ^-?[0-9]+$ ]] || die "database scalar type assertion failed" "expected integer" ;;
    uuid) is_uuid "$out" || die "database scalar type assertion failed" "expected UUID" ;;
    uuid_triplet)
      [[ "$out" =~ ^[0-9a-fA-F-]{36}\|[0-9a-fA-F-]{36}\|[0-9a-fA-F-]{36}$ ]] || die "database scalar type assertion failed" "expected UUID triplet"
      local a b c
      IFS='|' read -r a b c <<<"$out"
      is_uuid "$a" && is_uuid "$b" && is_uuid "$c" || die "database scalar type assertion failed" "expected UUID triplet"
      ;;
    uuid_quadruplet)
      [[ "$out" =~ ^[0-9a-fA-F-]{36}\|[0-9a-fA-F-]{36}\|[0-9a-fA-F-]{36}\|[0-9a-fA-F-]{36}$ ]] \
        || die "database scalar type assertion failed" "expected UUID quadruplet"
      local a b c d
      IFS='|' read -r a b c d <<<"$out"
      is_uuid "$a" && is_uuid "$b" && is_uuid "$c" && is_uuid "$d" \
        || die "database scalar type assertion failed" "expected UUID quadruplet"
      ;;
    subscription_tuple)
      local sub uid proxy version
      IFS='|' read -r sub uid proxy version <<<"$out"
      is_uuid "$sub" && [[ "$uid" =~ ^[0-9]+$ ]] && is_uuid "$proxy" && is_uuid "$version" \
        || die "database scalar type assertion failed" "expected subscription tuple"
      ;;
    identifier) [[ "$out" =~ ^[A-Za-z_][A-Za-z0-9_-]*$ ]] || die "database scalar type assertion failed" "expected identifier" ;;
    *) die "unknown database scalar type" ;;
  esac
  printf '%s' "$out"
}

# This script creates paid orders and immutable traffic/audit evidence. Complete
# reversal is not guaranteed by design, so it must only run against a disposable
# database whose loss has been explicitly acknowledged by the caller.
[ "${UNIPROXY_E2E_DISPOSABLE:-}" = "YES_DELETE_FIXTURES" ] \
  || die "refusing to run outside an explicitly disposable E2E database" \
    "set UNIPROXY_E2E_DISPOSABLE=YES_DELETE_FIXTURES"
[ -n "$ADMIN_EMAIL" ] || die "ADMIN_EMAIL must be provided explicitly"
[ -n "$ADMIN_PASS" ] || die "ADMIN_PASS must be provided explicitly"
require_loopback_url "$ADM" ADM
require_loopback_url "$NODE" NODE
require_loopback_url "$PUB" PUB
registration_parser_selftest || die "registration response parser self-test failed"
[ -n "$TENANT" ] && is_uuid "$TENANT" \
  || die "UNIPROXY_E2E_TENANT_ID must be an explicit UUID"
DB_NAME=$(db_scalar identifier "SELECT current_database()")
[[ "$DB_NAME" =~ (^|[-_])(test|e2e)([-_]|$) ]] \
  || die "database name is not recognizably disposable" "name must contain a standalone test or e2e segment"
[ "${UNIPROXY_E2E_DATABASE:-}" = "$DB_NAME" ] \
  || die "database identity acknowledgement does not match" "set UNIPROXY_E2E_DATABASE to the exact disposable database name"
TENANT_EXISTS=$(db_scalar integer "SELECT count(*) FROM tenants WHERE id='$TENANT'")
[ "$TENANT_EXISTS" = 1 ] || die "explicit E2E tenant does not exist exactly once"
E2E_PREFLIGHT_OK=1

#-------------------------------------------------------------------------------
sec "1. Prepare a schema-v1 serving Node"

expect_http 200 POST "$ADM/v1/auth/login" -H 'Content-Type: application/json' \
  -d "{\"email\":\"$ADMIN_EMAIL\",\"password\":\"$ADMIN_PASS\"}"
ATOK=$(json_get "$HTTP_BODY" access_token) || die "admin login response is invalid"
assert_nonempty "$ATOK" "admin authenticated"
AH="Authorization: Bearer $ATOK"

STAMP="$(date +%s)-$RANDOM"
FIXTURE=$(db_scalar uuid_triplet "
  WITH created_server AS (
    INSERT INTO servers (tenant_id,name,status,hostname,public_ipv4,capacity_nodes)
    VALUES ('$TENANT','uni-server-$STAMP','ready','uni-$STAMP.example.test','203.0.113.10',4)
    RETURNING id
  ), created_pool AS (
    INSERT INTO node_pools (tenant_id,code,name)
    VALUES ('$TENANT','uni-initial-$STAMP','UniProxy initial pool $STAMP')
    RETURNING id
  ), created_node AS (
    INSERT INTO nodes
      (tenant_id,name,server_id,pool_id,status,serving_status,node_type,server_host,
       server_port,kernel,traffic_rate,display_name,protocol_config,
       protocol_schema_version,config_validated_at,row_version)
    SELECT '$TENANT','uni-node-$STAMP',s.id,p.id,'draft','active','vless',
           'node.example.com',443,'auto',1.0,'Hong Kong 01',
           '{\"network\":\"tcp\",\"tls\":false}'::jsonb,1,now(),1
      FROM created_server s CROSS JOIN created_pool p
    RETURNING id,server_id,pool_id
  )
  SELECT id::text || '|' || server_id::text || '|' || pool_id::text FROM created_node")
IFS='|' read -r NODE_ID SERVER_ID INITIAL_POOL_ID <<<"$FIXTURE"
assert_nonempty "$NODE_ID" "stable fixture Node created"
assert_nonempty "$SERVER_ID" "fixture Server created"
assert_nonempty "$INITIAL_POOL_ID" "fixture pool created"

# Exercise the compatibility protocol endpoint with the current closed schema.
# tls=true, numeric tls and flow are intentionally not success samples.
expect_http 200 POST "$ADM/v1/nodes/$NODE_ID/protocol" -H "$AH" -H 'Content-Type: application/json' \
  -d '{"row_version":1,"node_type":"vless","server_host":"node.example.com","server_port":443,
       "kernel":"auto","traffic_rate":1.0,"display_name":"Hong Kong 01",
       "protocol_config":{"network":"tcp","tls":false}}'
json_check "$HTTP_BODY" \
  'd["node_type"] == "vless" and d["server_port"] == 443 and d["protocol_schema_version"] == 1 and d["config_validated_at"] is not None and d["row_version"] == 2' \
  "protocol update accepted only the stable v1 contract"
NODE_ROW_VERSION=2

# 签服务端令牌挂着幂等中间件（node_server_token_issue），缺 Idempotency-Key 回 400
expect_http 201 POST "$ADM/v1/nodes/$NODE_ID/server-token" -H "$AH" \
  -H "Idempotency-Key: uni-server-token-$STAMP"
TOKEN=$(json_get "$HTTP_BODY" token) || die "server-token response is invalid"
assert_nonempty "$TOKEN" "one-time UniProxy token issued"
[[ "$TOKEN" =~ ^[A-Za-z0-9_-]+$ ]] || die "server-token response used an unsafe token encoding"
TOKEN_STATE=$(db_scalar integer "SELECT CASE WHEN server_token_hash IS NOT NULL AND octet_length(server_token_hash)=32 THEN 1 ELSE 0 END FROM nodes WHERE id='$NODE_ID'")
assert_eq "$TOKEN_STATE" 1 "only a fixed-size token hash is stored"

Q="node_id=$NODE_ID&node_type=vless"
NAH="Authorization: Bearer $TOKEN"

#-------------------------------------------------------------------------------
sec "2. Node authentication"

expect_http 401 GET "$UNI/config?$Q" -H 'Authorization: Bearer wrong-token'
ok "wrong Bearer token rejected"
expect_http 401 GET "$UNI/config?$Q"
ok "missing token rejected"
expect_http 200 GET "$UNI/config?$Q&token=$TOKEN"
json_check "$HTTP_BODY" 'd["protocol"] == "vless" and d["server_port"] == 443' \
  "legacy query token remains a compatible positive authentication path"
expect_http 401 GET "$UNI/config?$Q&token=$TOKEN" -H 'Authorization: Bearer wrong-token'
ok "Bearer credentials take precedence over a valid query token"
expect_http 401 GET "$UNI/config?$Q&token=$TOKEN" -H 'Authorization: Basic malformed'
ok "malformed explicit Authorization does not downgrade to query authentication"
FAKE=$(python3 -c 'import uuid; print(uuid.uuid4())')
expect_http 401 GET "$UNI/config?node_id=$FAKE&node_type=vless" -H "$NAH"
ok "unknown Node and bad credentials are indistinguishable"

#-------------------------------------------------------------------------------
sec "3. Config and ETag contract"

expect_http 200 GET "$UNI/config?$Q" -H "$NAH"
CFG=$HTTP_BODY
json_check "$CFG" \
  'd["protocol"] == "vless" and d["server_port"] == 443 and d["network"] == "tcp" and d["tls"] is False and d["base_config"]["push_interval"] == 60' \
  "config response contains the required UniProxy fields"
ETAG=$(printf '%s\n' "$HTTP_HEADERS" | awk 'BEGIN{IGNORECASE=1} /^ETag:/{sub(/\r$/, ""); print $2}' | tail -1)
assert_nonempty "$ETAG" "config returned ETag"

expect_http 304 GET "$UNI/config?$Q" -H "$NAH" -H "If-None-Match: $ETAG"
[ -z "$HTTP_BODY" ] || die "304 response unexpectedly contained a body"
ok "matching ETag returned an empty 304 response"

expect_http 200 POST "$ADM/v1/nodes/$NODE_ID/protocol" -H "$AH" -H 'Content-Type: application/json' \
  -d "{\"row_version\":$NODE_ROW_VERSION,\"node_type\":\"vless\",\"server_host\":\"node.example.com\",\"server_port\":8443,
       \"kernel\":\"auto\",\"traffic_rate\":1.5,\"display_name\":\"Hong Kong 01\",
       \"protocol_config\":{\"network\":\"tcp\",\"tls\":false}}"
json_check "$HTTP_BODY" 'd["server_port"] == 8443 and d["traffic_rate"] == 1.5 and d["row_version"] == 3' \
  "valid protocol change returned the new row version"
NODE_ROW_VERSION=3

expect_http 200 GET "$UNI/config?$Q" -H "$NAH"
ETAG2=$(printf '%s\n' "$HTTP_HEADERS" | awk 'BEGIN{IGNORECASE=1} /^ETag:/{sub(/\r$/, ""); print $2}' | tail -1)
[ -n "$ETAG2" ] && [ "$ETAG2" != "$ETAG" ] || die "config ETag did not change" "$ETAG -> $ETAG2"
json_check "$HTTP_BODY" 'd["server_port"] == 8443' "changed config is visible to the Node"

# Runtime status is part of the UniProxy compatibility surface.
expect_http 200 POST "$UNI/status?$Q" -H "$NAH" -H 'Content-Type: application/json' \
  -d '{"cpu":12.5,"mem":{"total":1073741824,"used":536870912},
       "swap":{"total":0,"used":0},"disk":{"total":10737418240,"used":2147483648}}'
json_check "$HTTP_BODY" 'd["data"] is True' "runtime status report acknowledged"
METRICS=$(db_scalar integer "SELECT count(*) FROM node_metrics WHERE node_id='$NODE_ID' AND cpu_bp=1250")
[ "$METRICS" -ge 1 ] || die "runtime status was not persisted" "count=$METRICS"
ok "runtime status persisted coarse metrics"

#-------------------------------------------------------------------------------
sec "4. Create an eligible subscription"

UE="uni_${STAMP}_$RANDOM@example.com"
expect_http 200 POST "$PUB/v1/auth/register/start" -H 'Content-Type: application/json' -d "{\"email\":\"$UE\"}"
START_FIELDS=$(parse_registration_start "$HTTP_BODY" 2>/dev/null) \
  || die "registration start response invalid"
mapfile -t REG_FIELDS <<<"$START_FIELDS"
[ "${#REG_FIELDS[@]}" -eq 3 ] || die "registration start response invalid"
RT=${REG_FIELDS[0]}; VR=${REG_FIELDS[1]}; CD=${REG_FIELDS[2]}
[ "$CD" = - ] && CD=
REGISTRATION_ID=$(db_scalar uuid "SELECT id FROM registration_sessions WHERE tenant_id='$TENANT' AND email='$UE'")
# Registration completion and login emit immutable security/audit evidence.
# From this boundary onward, the mandatory disposable database—not individual
# fixture rows—is the supported cleanup unit.
DISPOSABLE_RESIDUE_EXPECTED=1
expect_http 201 POST "$PUB/v1/auth/register/complete" -H 'Content-Type: application/json' \
  -d "{\"registration_token\":\"$RT\",\"code\":\"$CD\",\"password\":\"UniPass2026\"}"
USER_ID=$(json_get "$HTTP_BODY" user_id) || die "registration response missing user id"
is_uuid "$USER_ID" || die "registration response returned an invalid user id"
assert_nonempty "$USER_ID" "test user registered"
expect_http 200 POST "$PUB/v1/auth/login" -H 'Content-Type: application/json' \
  -d "{\"email\":\"$UE\",\"password\":\"UniPass2026\"}"
UTOK=$(json_get "$HTTP_BODY" access_token) || die "user login response invalid"

expect_http 200 GET "$PUB/v1/plans" -H "Authorization: Bearer $UTOK"
CATALOG=$(db_scalar uuid_quadruplet "
  SELECT p.id::text || '|' || pr.id::text || '|' || pv.id::text || '|' || pnp.pool_id::text
    FROM plans p
    JOIN plan_versions pv ON pv.tenant_id=p.tenant_id AND pv.id=p.current_version_id
    JOIN prices pr ON pr.tenant_id=p.tenant_id AND pr.product_id=p.product_id
    JOIN plan_node_pools pnp ON pnp.tenant_id=p.tenant_id AND pnp.plan_version_id=pv.id
    JOIN node_pools np ON np.tenant_id=pnp.tenant_id AND np.id=pnp.pool_id
   WHERE p.tenant_id='$TENANT' AND p.status='active'
     AND p.visibility IN ('public','authenticated') AND p.allow_new_purchase
     AND (p.visible_from IS NULL OR p.visible_from<=now())
     AND (p.visible_until IS NULL OR p.visible_until>now())
     AND (p.stock_total IS NULL OR p.stock_sold+p.stock_reserved<p.stock_total)
     AND pv.status='published' AND pv.frozen_at IS NOT NULL
     AND pr.currency='CNY' AND pr.status='active' AND pr.user_group_id IS NULL
     AND (pr.valid_from IS NULL OR pr.valid_from<=now())
     AND (pr.valid_until IS NULL OR pr.valid_until>now())
     AND np.status<>'disabled'
   ORDER BY p.sort_order,p.id,pr.id,pnp.pool_id LIMIT 1")
IFS='|' read -r PLAN PRICE PV ELIGIBLE_POOL_ID <<<"$CATALOG"
json_check "$HTTP_BODY" \
  "any(p['id'] == '$PLAN' and any(x['id'] == '$PRICE' and x['currency'] == 'CNY' for x in p['prices']) for p in d['plans'])" \
  "eligible bound plan is visible in the public catalog"
UPDATED=$(db_scalar integer "WITH u AS (UPDATE nodes SET pool_id='$ELIGIBLE_POOL_ID'
  WHERE tenant_id='$TENANT' AND id='$NODE_ID' RETURNING 1) SELECT count(*) FROM u")
assert_eq "$UPDATED" 1 "Node moved to the selected plan's eligible pool"

expect_http 201 POST "$PUB/v1/orders" -H "Authorization: Bearer $UTOK" -H 'Content-Type: application/json' \
  -H "Idempotency-Key: uni-order-$STAMP-$RANDOM" \
  -d "{\"plan_id\":\"$PLAN\",\"price_id\":\"$PRICE\",\"use_balance\":0}"
ORDER_ID=$(json_get "$HTTP_BODY" order_id) || die "order response missing order id"
is_uuid "$ORDER_ID" || die "order response returned an invalid order id"
ONO=$(json_get "$HTTP_BODY" order_no) || die "order response missing order number"
PAYABLE=$(json_get "$HTTP_BODY" payable_amount) || die "order response missing payable amount"
[[ "$ONO" =~ ^[A-Za-z0-9_-]+$ ]] || die "order response returned an unsafe order number"
[[ "$PAYABLE" =~ ^[0-9]+$ ]] || die "order response returned a non-integer payable amount"

TN="UNI$(date +%s)$RANDOM"
MONEY=$(python3 -c "print(f'{int($PAYABLE)//100}.{int($PAYABLE)%100:02d}')" 2>/dev/null) \
  || die "failed to format the disposable payment amount"
[[ "$MONEY" =~ ^[0-9]+\.[0-9]{2}$ ]] || die "formatted payment amount was invalid"
SG=$(python3 -c "
import hashlib
p={'pid':'1001','trade_no':'$TN','out_trade_no':'$ONO','type':'alipay','money':'$MONEY','trade_status':'TRADE_SUCCESS'}
print(hashlib.md5(('&'.join(f'{k}={p[k]}' for k in sorted(p))+'TESTKEY_e2e_20260725').encode()).hexdigest())" 2>/dev/null) \
  || die "failed to sign the disposable payment fixture"
[[ "$SG" =~ ^[0-9a-f]{32}$ ]] || die "payment fixture signature generation returned an invalid digest"
expect_http 200 GET "$PUB/v1/webhooks/payments/epay?pid=1001&trade_no=$TN&out_trade_no=$ONO&type=alipay&money=$MONEY&trade_status=TRADE_SUCCESS&sign=$SG&sign_type=MD5"
assert_eq "$HTTP_BODY" success "payment webhook completed the subscription"

SUB_ROW=$(db_scalar subscription_tuple "SELECT id::text || '|' || node_uid::text || '|' || proxy_uuid::text || '|' || plan_version_id::text
  FROM subscriptions WHERE user_id=(SELECT id FROM users WHERE email='$UE')")
IFS='|' read -r SUB_ID NODE_UID PROXY_UUID PV <<<"$SUB_ROW"
assert_nonempty "$SUB_ID" "subscription created"
assert_nonempty "$NODE_UID" "subscription has a UniProxy UID"
assert_nonempty "$PROXY_UUID" "subscription has a proxy UUID"

expect_http 200 GET "$UNI/user?$Q" -H "$NAH"
json_check "$HTTP_BODY" \
  "any(str(u['id']) == '$NODE_UID' and u['uuid'] == '$PROXY_UUID' for u in d['users'])" \
  "eligible subscription appears in the user response"

#-------------------------------------------------------------------------------
sec "5. User eligibility and Node service status"

UPDATED=$(db_scalar integer "WITH u AS (UPDATE quota_balances SET consumed=COALESCE(limit_value,0)+granted_addon+adjusted+1
  WHERE subscription_id='$SUB_ID' AND metric='traffic.bytes' RETURNING 1) SELECT count(*) FROM u")
assert_eq "$UPDATED" 1 "traffic quota fixture exhausted exactly one balance"
expect_http 200 GET "$UNI/user?$Q" -H "$NAH"
json_check "$HTTP_BODY" "not any(str(u['id']) == '$NODE_UID' for u in d['users'])" "quota-exhausted user is withheld"

UPDATED=$(db_scalar integer "WITH u AS (UPDATE quota_balances SET consumed=0
  WHERE subscription_id='$SUB_ID' AND metric='traffic.bytes' RETURNING 1) SELECT count(*) FROM u")
assert_eq "$UPDATED" 1 "quota reset updated exactly one balance"
expect_http 200 GET "$UNI/user?$Q" -H "$NAH"
json_check "$HTTP_BODY" "any(str(u['id']) == '$NODE_UID' for u in d['users'])" "user returns after quota reset"

UPDATED=$(db_scalar integer "WITH u AS (UPDATE subscriptions SET current_period_start=now()-interval '31 days',
  current_period_end=now()-interval '1 day' WHERE id='$SUB_ID' RETURNING 1) SELECT count(*) FROM u")
assert_eq "$UPDATED" 1 "subscription expiry fixture updated exactly one row"
expect_http 200 GET "$UNI/user?$Q" -H "$NAH"
json_check "$HTTP_BODY" "not any(str(u['id']) == '$NODE_UID' for u in d['users'])" "expired user is withheld"
UPDATED=$(db_scalar integer "WITH u AS (UPDATE subscriptions SET current_period_start=now()-interval '1 day',
  current_period_end=now()+interval '30 days' WHERE id='$SUB_ID' RETURNING 1) SELECT count(*) FROM u")
assert_eq "$UPDATED" 1 "subscription period restored exactly one row"

UNAUTH_POOL_ID=$(db_scalar uuid "INSERT INTO node_pools (tenant_id,code,name)
  VALUES ('$TENANT','uni-unauthorized-$STAMP','UniProxy unauthorized pool $STAMP') RETURNING id")
UPDATED=$(db_scalar integer "WITH u AS (UPDATE nodes SET pool_id='$UNAUTH_POOL_ID' WHERE id='$NODE_ID' RETURNING 1) SELECT count(*) FROM u")
assert_eq "$UPDATED" 1 "Node moved to an unauthorized pool"
expect_http 200 GET "$UNI/user?$Q" -H "$NAH"
json_check "$HTTP_BODY" "not any(str(u['id']) == '$NODE_UID' for u in d['users'])" "plan pool isolation withholds the user"
UPDATED=$(db_scalar integer "WITH u AS (UPDATE nodes SET pool_id='$ELIGIBLE_POOL_ID'
  WHERE tenant_id='$TENANT' AND id='$NODE_ID' RETURNING 1) SELECT count(*) FROM u")
assert_eq "$UPDATED" 1 "Node restored to the plan's immutable eligible pool"
expect_http 200 GET "$UNI/user?$Q" -H "$NAH"
json_check "$HTTP_BODY" "any(str(u['id']) == '$NODE_UID' for u in d['users'])" "eligible pool restoration returns the user"

expect_http 200 POST "$ADM/v1/nodes/status:batch" -H "$AH" -H 'Content-Type: application/json' \
  -H "Idempotency-Key: uni-disable-$STAMP" \
  -d "{\"items\":[{\"id\":\"$NODE_ID\",\"row_version\":$NODE_ROW_VERSION}],\"serving_status\":\"disabled\",\"reason\":\"e2e gate\"}"
json_check "$HTTP_BODY" 'd["updated"] == 1 and d["serving_status"] == "disabled"' "Node disabled through the admin lifecycle API"
NODE_ROW_VERSION=$((NODE_ROW_VERSION + 1))
expect_http 401 GET "$UNI/user?$Q" -H "$NAH"
ok "disabled logical Node cannot authenticate to UniProxy"

expect_http 200 POST "$ADM/v1/nodes/status:batch" -H "$AH" -H 'Content-Type: application/json' \
  -H "Idempotency-Key: uni-enable-$STAMP" \
  -d "{\"items\":[{\"id\":\"$NODE_ID\",\"row_version\":$NODE_ROW_VERSION}],\"serving_status\":\"active\",\"reason\":\"e2e restore\"}"
json_check "$HTTP_BODY" 'd["updated"] == 1 and d["serving_status"] == "active"' "Node restored through the admin lifecycle API"
NODE_ROW_VERSION=$((NODE_ROW_VERSION + 1))

#-------------------------------------------------------------------------------
sec "6. Traffic reporting and deduplication"

UPDATED=$(db_scalar integer "WITH u AS (UPDATE nodes SET traffic_rate=1.0 WHERE id='$NODE_ID' RETURNING 1) SELECT count(*) FROM u")
assert_eq "$UPDATED" 1 "traffic rate baseline updated exactly one Node"
BEFORE=$(db_scalar integer "SELECT consumed FROM quota_balances WHERE subscription_id='$SUB_ID' AND metric='traffic.bytes'")
PAYLOAD="{\"$NODE_UID\":[1048576,2097152]}"
expect_http 200 POST "$UNI/push?$Q" -H "$NAH" -H 'Content-Type: application/json' -d "$PAYLOAD"
json_check "$HTTP_BODY" 'd["data"] is True and d["accepted"] == 1' "traffic report accepted"
AFTER=$(db_scalar integer "SELECT consumed FROM quota_balances WHERE subscription_id='$SUB_ID' AND metric='traffic.bytes'")
assert_eq "$((AFTER - BEFORE))" 3145728 "traffic usage billed upload plus download"

NREP=$(db_scalar integer "SELECT count(*) FROM node_traffic_reports WHERE node_id='$NODE_ID'")
[ "$NREP" -ge 1 ] || die "traffic report was not archived" "count=$NREP"
ok "traffic report archived"

expect_http 200 POST "$UNI/push?$Q" -H "$NAH" -H 'Content-Type: application/json' -d "$PAYLOAD"
json_check "$HTTP_BODY" 'd["data"] is True and d["accepted"] == 0' "duplicate traffic report acknowledged without acceptance"
AFTER2=$(db_scalar integer "SELECT consumed FROM quota_balances WHERE subscription_id='$SUB_ID' AND metric='traffic.bytes'")
assert_eq "$AFTER2" "$AFTER" "duplicate report did not bill twice"
NDUP=$(db_scalar integer "SELECT count(*) FROM node_traffic_reports WHERE node_id='$NODE_ID' AND duplicate_of IS NOT NULL")
[ "$NDUP" -ge 1 ] || die "duplicate traffic report was not marked" "count=$NDUP"
ok "duplicate traffic report retained with duplicate_of"

UPDATED=$(db_scalar integer "WITH u AS (UPDATE nodes SET traffic_rate=2.0 WHERE id='$NODE_ID' RETURNING 1) SELECT count(*) FROM u")
assert_eq "$UPDATED" 1 "traffic multiplier fixture updated exactly one Node"
sleep 11
B3=$(db_scalar integer "SELECT consumed FROM quota_balances WHERE subscription_id='$SUB_ID' AND metric='traffic.bytes'")
expect_http 200 POST "$UNI/push?$Q" -H "$NAH" -H 'Content-Type: application/json' \
  -d "{\"$NODE_UID\":[1048576,0]}"
json_check "$HTTP_BODY" 'd["accepted"] == 1' "traffic report with multiplier accepted"
A3=$(db_scalar integer "SELECT consumed FROM quota_balances WHERE subscription_id='$SUB_ID' AND metric='traffic.bytes'")
assert_eq "$((A3 - B3))" 2097152 "traffic multiplier applied"
UPDATED=$(db_scalar integer "WITH u AS (UPDATE nodes SET traffic_rate=1.0 WHERE id='$NODE_ID' RETURNING 1) SELECT count(*) FROM u")
assert_eq "$UPDATED" 1 "traffic rate restored exactly one Node"

sleep 11
expect_http 200 POST "$UNI/push?$Q" -H "$NAH" -H 'Content-Type: application/json' \
  -d "{\"999999999\":[100,100],\"$NODE_UID\":[1024,1024]}"
json_check "$HTTP_BODY" 'd["accepted"] == 1' "unknown UID skipped while valid UID was accepted"

#-------------------------------------------------------------------------------
sec "7. Online and runtime reports"

expect_http 200 POST "$UNI/alive?$Q" -H "$NAH" -H 'Content-Type: application/json' \
  -d "{\"$NODE_UID\":[\"1.2.3.4\",\"5.6.7.8\"]}"
json_check "$HTTP_BODY" 'd["data"] is True and d["ips"] == 2' "online report acknowledged both IPs"
NIP=$(db_scalar integer "SELECT count(*) FROM node_alive_ips WHERE node_id='$NODE_ID' AND subscription_id='$SUB_ID'")
assert_eq "$NIP" 2 "online IP hashes persisted"
RAW=$(db_scalar integer "SELECT count(*) FROM node_alive_ips WHERE node_id='$NODE_ID' AND encode(ip_hash,'escape') LIKE '%1.2.3.4%'")
assert_eq "$RAW" 0 "raw IP was not stored"

expect_http 200 POST "$UNI/alive?$Q" -H "$NAH" -H 'Content-Type: application/json' \
  -d "{\"$NODE_UID\":[\"1.2.3.4\"]}"
json_check "$HTTP_BODY" 'd["ips"] == 1' "repeat online report acknowledged"
NIP2=$(db_scalar integer "SELECT count(*) FROM node_alive_ips WHERE node_id='$NODE_ID' AND subscription_id='$SUB_ID'")
assert_eq "$NIP2" 2 "repeat online report did not create a duplicate row"

#-------------------------------------------------------------------------------
sec "8. Cleanup lifecycle"

DELETED=$(db_scalar integer "WITH d AS (DELETE FROM node_alive_ips WHERE node_id='$NODE_ID' RETURNING 1) SELECT count(*) FROM d")
assert_eq "$DELETED" 2 "online fixture cleanup deleted exactly two IP hashes"
expect_http 200 POST "$ADM/v1/nodes/status:batch" -H "$AH" -H 'Content-Type: application/json' \
  -H "Idempotency-Key: uni-drain-$STAMP" \
  -d "{\"items\":[{\"id\":\"$NODE_ID\",\"row_version\":$NODE_ROW_VERSION}],\"serving_status\":\"draining\",\"reason\":\"e2e cleanup\"}"
json_check "$HTTP_BODY" 'd["updated"] == 1 and d["serving_status"] == "draining"' "test Node entered draining state"
NODE_ROW_VERSION=$((NODE_ROW_VERSION + 1))
expect_http 200 POST "$ADM/v1/nodes/status:batch" -H "$AH" -H 'Content-Type: application/json' \
  -H "Idempotency-Key: uni-retire-$STAMP" \
  -d "{\"items\":[{\"id\":\"$NODE_ID\",\"row_version\":$NODE_ROW_VERSION}],\"serving_status\":\"retired\",\"reason\":\"e2e cleanup\"}"
json_check "$HTTP_BODY" 'd["updated"] == 1 and d["serving_status"] == "retired"' "test Node retired"
